---
- name: Create instances
  os_server:
    name: "{{ item.name }}"
    state: present
    key_name: "{{ item.key }}"
    image: "{{ item.image }}"
    flavor: "{{ item.flavor }}"
    security_groups:  "{{ item.security_groups }}"
    auto_floating_ip: yes
    floating_ips: "{{ item.floating_ips | default(omit) }}"
    network: "{{ item.network }}"
    nics: "{{ item.nics | default(omit) }}"
    availability_zone: "{{ item.availability_zone | default(omit) }}"
    wait: yes
  with_items: "{{ servers }}"
  register: "os_hosts"


- name: debug
  debug:
    msg: "{{ os_hosts.results }}"

#  add_host:
#    name: "{{ item['openstack']['human_id'] }}"
#    groups: "{{ item['item']['meta']['group'] }}"
#    ansible_host: "{{ item.openstack.accessIPv4 }}"
#  with_items: "{{ os_hosts.results }}"
