---
- name: register flavors
  os_nova_flavor:
    name: "{{ item.name }}"
    ram: "{{ item.ram }}"
    vcpus: "{{ item.vcpus }}"
    disk: "{{ item.disk }}"
    ephemeral: "{{ item.ephemeral | default(omit) }}"
    swap: "{{ item.swap | default(omit) }}"
    is_public: "{{ item.is_public | default(omit) }}"
    extra_specs: "{{ item.extra_specs | default(omit) }}"
    state: present
  with_items: "{{ flavors }}"
